yaml

# _config.yml
plugins:
  - jekyll-optional-front-matter

# Configure MIME types
defaults:
  - scope:
      path: ".well-known/com.apple.remotemanagement"
    values:
      content_type: "application/json"

# Include the .well-known directory
include:
  - .well-known
